# Generated by Django 4.2.5 on 2023-09-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.TextField(default=1, verbose_name='why?'),
            preserve_default=False,
        ),
    ]
